### ISSUE TITLE
First time using error: Cannot read property 'Symbol(Symbol.iterator)' of undefined

### ISSUE THREAD

**Issue by tnimas** [kasami/mastermind#1]
Hi guys, i'm currently looking for different screeps AI's to use on my private server. I see your AI is pretty huge and fresh so i want to try it. However there's an in game error i can't easily fix. 

I did:
gulp build --target local
then i placed main.js to a branch and chose it in game.

Here's the error:
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at OperationManager.runMissions (main:10040:36)
    at OperationManager.run (main:10026:23)
    at logUsedCpu (main:220:24)
    at Object.run (main:148:10)
    at Object.loop (main:56:11)
    at __mainLoop:1:52
    at sigintHandlersWrap (vm.js:32:31)
    at sigintHandlersWrap (vm.js:96:12)

I believe it's about Memory.missions field that always becomes undefined for me when i try to change it.

Could you please tell me what can i do about this if it's possible?

**Comment by kasami** [comment]
The AI is a work in progress, and will probably not work as a bit. I haven't even tried it outside of the main world.

I might look into it in the future, but as it stands, I don't think it will work.
